version: '3.7'

networks:
  default:
    external: true
    name: lb-common

services:
  cerbos:
    image: ghcr.io/cerbos/cerbos:0.26.0
    deploy:
      replicas: 1
      labels:
        traefik.frontend.rule: "Host:cerbos.local.io,cerbos.local.com"
        traefik.enable: "true"
        traefik.backend: "cerbos_back"
        traefik.port: "3592"
        traefik.backend.healthcheck.path: /
        traefik.backend.healthcheck.interval: 1s
        traefik.backend.healthcheck.port: 3592
        traefik.backend.healthcheck.scheme: http
    networks:
      - default
    volumes:
      - ./policies:/policies
      - ./config:/config
